services:
  streamlit-content-minio:
      image: minio/minio:latest
      container_name: streamLit-content-minio
      restart: always
      ports:
        - "9000:9000"   # API port
        - "9001:9001"   # Console port
      environment:
        MINIO_ROOT_USER: ${MINIO_SONG_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_SONG_ROOT_PASSWORD}
      command: server /data --console-address ":9001"
      volumes:
        - H:/minio/data:/data